Pivot Table

In [1]:
import pandas as pd
import numpy as np

In [2]:

import random

data = {
    "Date": [
        f"2026-{random.randint(1, 12):02d}-{random.randint(1, 28):02d}"
        for _ in range(1000)
    ],

    "Product": [
        random.choice([
            "Laptop",
            "Mobile",
            "Tablet",
            "Headphones",
            "Keyboard",
            "Mouse",
            "Monitor",
            "Printer",
            "Smartwatch",
            "Camera"
        ])
        for _ in range(1000)
    ],

    "Region": [
        random.choice([
            "North",
            "South",
            "East",
            "West",
            "Central"
        ])
        for _ in range(1000)
    ],

    "Sales": [
        round(random.uniform(500, 100000), 2)
        for _ in range(1000)
    ],

    "Units": [
        random.randint(1, 100)
        for _ in range(1000)
    ]
}

df = pd.DataFrame(data)

# Convert Date column to datetime
df["Date"] = pd.to_datetime(df["Date"])

print(df)

          Date   Product   Region     Sales  Units
0   2026-02-26    Laptop    South  10310.61     85
1   2026-12-02    Camera    North  34347.86     93
2   2026-06-13    Laptop  Central  68049.97     10
3   2026-01-12    Mobile    North  86415.92     50
4   2026-05-10   Monitor  Central  34491.10     63
..         ...       ...      ...       ...    ...
995 2026-10-06    Mobile     West  68634.12     27
996 2026-04-19    Laptop     East  69932.98     45
997 2026-10-08    Mobile     West  58312.46     32
998 2026-08-20  Keyboard     East  13070.05     96
999 2026-06-07   Monitor    North   6445.83     72

[1000 rows x 5 columns]

In [ ]:
### Check null value at first
df.isna().sum()

Date       0
Product    0
Region     0
Sales      0
Units      0
dtype: int64

In [7]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc="median")

Product,Camera,Headphones,Keyboard,Laptop,Mobile,Monitor,Mouse,Printer,Smartwatch,Tablet
Region,,,,,,,,,,
Central,63337.440,38055.290,62275.325,40791.95,37474.610,37185.550,48619.945,47233.54,52004.230,36509.560
East,54842.005,50388.130,25697.035,57133.00,35964.880,59351.175,65358.920,41234.26,61460.670,32484.460
North,31592.505,44787.755,58296.275,42425.99,63621.095,42149.690,54803.275,58964.07,56663.405,45911.000
South,52121.180,72773.805,71842.590,52798.34,53346.380,46665.310,54329.920,48481.50,61554.800,42588.450
West,30632.610,43877.500,45115.130,66251.84,68479.125,40574.425,42975.320,58799.94,40382.925,58395.225

In [8]:
pd.pivot_table(df,values=["Sales","Units"],index="Region",columns="Product",aggfunc="median")

             Sales                                                        \
Product     Camera Headphones   Keyboard    Laptop     Mobile    Monitor
Region
Central  63337.440  38055.290  62275.325  40791.95  37474.610  37185.550
East     54842.005  50388.130  25697.035  57133.00  35964.880  59351.175
North    31592.505  44787.755  58296.275  42425.99  63621.095  42149.690
South    52121.180  72773.805  71842.590  52798.34  53346.380  46665.310
West     30632.610  43877.500  45115.130  66251.84  68479.125  40574.425

                                                    Units                      \
Product      Mouse   Printer Smartwatch     Tablet Camera Headphones Keyboard
Region
Central  48619.945  47233.54  52004.230  36509.560   67.0       37.5     51.5
East     65358.920  41234.26  61460.670  32484.460   45.0       38.5     34.0
North    54803.275  58964.07  56663.405  45911.000   54.0       60.5     43.0
South    54329.920  48481.50  61554.800  42588.450   59.0       46.5     55.0
West     42975.320  58799.94  40382.925  58395.225   44.0       40.0     51.0


Product Laptop Mobile Monitor Mouse Printer Smartwatch Tablet
Region
Central   55.0   52.5    42.0  38.5    39.5       49.0   57.5
East      45.0   51.0    47.5  25.0    59.5       52.0   28.0
North     46.0   52.0    43.0  40.0    65.0       66.5   65.0
South     47.0   60.0    52.0  39.0    57.0       71.0   50.0
West      66.0   56.0    51.5  46.0    42.0       63.5   59.5

cross Table

In [ ]:
### It  use for counting Tables
pd.crosstab(df["Region"],df["Product"])

Product,Camera,Headphones,Keyboard,Laptop,Mobile,Monitor,Mouse,Printer,Smartwatch,Tablet
Region,,,,,,,,,,
Central,12,24,22,19,20,21,18,16,25,22
East,24,18,20,21,25,18,17,34,24,23
North,22,20,18,19,28,20,14,15,28,21
South,25,22,14,13,19,17,26,17,13,21
West,21,23,21,21,14,22,11,16,22,14